export const DEMO_CAPACITY = 12;

export const DEMO_MEMBER = {
  name: "Marie",
  fullName: "Marie Laurent",
  email: "marie.laurent@gmail.com",
  plan: "Carte 10 séances",
  credits: 6,
  renewal: "Valable jusqu'au 31 août",
};

export const MEMBERSHIP_PLANS = [
  {
    id: "discovery",
    name: "Séance découverte",
    price: "15 €",
    description: "Une première séance pour découvrir le lieu, l'équipe et le fonctionnement.",
    detail: "1 séance",
  },
  {
    id: "single",
    name: "Séance à l'unité",
    price: "18 €",
    description: "Pour venir ponctuellement, sans abonnement.",
    detail: "1 séance",
  },
  {
    id: "card",
    name: "Carte de 10 séances",
    price: "150 €",
    description: "Dix séances à utiliser librement pendant la période de validité.",
    detail: "10 séances",
    popular: true,
  },
  {
    id: "regular",
    name: "Abonnement régulier",
    price: "89 € / mois",
    description: "Un rythme régulier pour progresser semaine après semaine.",
    detail: "3 séances / semaine",
  },
  {
    id: "unlimited",
    name: "Abonnement illimité",
    price: "119 € / mois",
    description: "Pour profiter librement des cours collectifs disponibles.",
    detail: "Accès illimité",
  },
  {
    id: "personal",
    name: "Coaching individuel",
    price: "55 € / séance",
    description: "Un accompagnement construit autour de vos besoins et de votre progression.",
    detail: "Sur rendez-vous",
  },
];

export type DemoSession = {
  id: string;
  dayKey: string;
  day: string;
  date: string;
  time: string;
  type: string;
  coach: string;
  booked: number;
  capacity: number;
  duration: string;
  level: string;
  hyrox?: boolean;
};

export const DEMO_DAYS = [
  { key: "lun-8", short: "Lun. 8", full: "Lundi 8 juin" },
  { key: "mar-9", short: "Mar. 9", full: "Mardi 9 juin" },
  { key: "mer-10", short: "Mer. 10", full: "Mercredi 10 juin" },
  { key: "jeu-11", short: "Jeu. 11", full: "Jeudi 11 juin" },
  { key: "ven-12", short: "Ven. 12", full: "Vendredi 12 juin" },
  { key: "sam-13", short: "Sam. 13", full: "Samedi 13 juin" },
];

export const DEMO_SESSIONS: DemoSession[] = [
  {
    id: "1",
    dayKey: "lun-8",
    day: "Lun.",
    date: "8 juin",
    time: "07:00",
    type: "Training collectif",
    coach: "Armel",
    booked: 8,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Tous niveaux",
  },
  {
    id: "2",
    dayKey: "lun-8",
    day: "Lun.",
    date: "8 juin",
    time: "08:15",
    type: "Renforcement",
    coach: "Sandra",
    booked: 5,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Tous niveaux",
  },
  {
    id: "3",
    dayKey: "lun-8",
    day: "Lun.",
    date: "8 juin",
    time: "18:00",
    type: "Préparation HYROX",
    coach: "Sandra",
    booked: 11,
    capacity: DEMO_CAPACITY,
    duration: "75 min",
    level: "Adaptable",
    hyrox: true,
  },
  {
    id: "4",
    dayKey: "lun-8",
    day: "Lun.",
    date: "8 juin",
    time: "19:30",
    type: "Mobilité",
    coach: "Sandra",
    booked: 6,
    capacity: DEMO_CAPACITY,
    duration: "45 min",
    level: "Tous niveaux",
  },
  {
    id: "5",
    dayKey: "mar-9",
    day: "Mar.",
    date: "9 juin",
    time: "07:00",
    type: "Full body",
    coach: "Sandra",
    booked: 7,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Tous niveaux",
  },
  {
    id: "6",
    dayKey: "mar-9",
    day: "Mar.",
    date: "9 juin",
    time: "18:30",
    type: "Force & technique",
    coach: "Armel",
    booked: 10,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Adaptable",
  },
  {
    id: "7",
    dayKey: "mer-10",
    day: "Mer.",
    date: "10 juin",
    time: "08:00",
    type: "Mobilité",
    coach: "Sandra",
    booked: 4,
    capacity: DEMO_CAPACITY,
    duration: "45 min",
    level: "Tous niveaux",
  },
  {
    id: "8",
    dayKey: "mer-10",
    day: "Mer.",
    date: "10 juin",
    time: "18:30",
    type: "Préparation HYROX",
    coach: "Armel",
    booked: 9,
    capacity: DEMO_CAPACITY,
    duration: "75 min",
    level: "Adaptable",
    hyrox: true,
  },
  {
    id: "9",
    dayKey: "jeu-11",
    day: "Jeu.",
    date: "11 juin",
    time: "07:00",
    type: "Training collectif",
    coach: "Armel",
    booked: 3,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Tous niveaux",
  },
  {
    id: "10",
    dayKey: "jeu-11",
    day: "Jeu.",
    date: "11 juin",
    time: "19:00",
    type: "Endurance",
    coach: "Sandra",
    booked: 8,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Adaptable",
  },
  {
    id: "11",
    dayKey: "ven-12",
    day: "Ven.",
    date: "12 juin",
    time: "07:00",
    type: "Full body",
    coach: "Armel",
    booked: 6,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Tous niveaux",
  },
  {
    id: "12",
    dayKey: "ven-12",
    day: "Ven.",
    date: "12 juin",
    time: "18:30",
    type: "Préparation HYROX",
    coach: "Sandra",
    booked: 12,
    capacity: DEMO_CAPACITY,
    duration: "75 min",
    level: "Adaptable",
    hyrox: true,
  },
  {
    id: "13",
    dayKey: "sam-13",
    day: "Sam.",
    date: "13 juin",
    time: "09:00",
    type: "Team training",
    coach: "Sandra & Armel",
    booked: 10,
    capacity: DEMO_CAPACITY,
    duration: "75 min",
    level: "Tous niveaux",
  },
  {
    id: "14",
    dayKey: "sam-13",
    day: "Sam.",
    date: "13 juin",
    time: "10:30",
    type: "Initiation",
    coach: "Armel",
    booked: 5,
    capacity: DEMO_CAPACITY,
    duration: "60 min",
    level: "Débutant",
  },
];

export const UPCOMING_BOOKINGS = [
  { id: "b1", date: "Lundi 8 juin", time: "18:00", type: "Préparation HYROX", coach: "Sandra" },
  { id: "b2", date: "Mercredi 10 juin", time: "08:00", type: "Mobilité", coach: "Sandra" },
];
